#!/bin/sh

# Launches all available test suites. Takes no arguments.
#
# The goal of this file is to automatically check all the test suites and to
# display the failed one. In this folder where this script is, all folders
# should be test suites.


# This exit code is defined in test-one to denote from the diff command exit
# one.
# NOTE: update the value here if this is changed in test-one.
ERROR_TEST=113

cd "$(dirname $0)"

for f in *; do
    if [ -d "$f" ]; then
        ./test-one "$f" > /dev/null
        exit_code="$?"
        if [ $exit_code -eq $ERROR_TEST ]; then
            printf "FAIL: \"%s\" test suite is ill-formed.\n" "$f"
        elif [ $exit_code -ne 0 ]; then
            printf "FAIL: \"%s\" test suite does not return the expected result.\n" "$f"
        fi
    fi
done
